---
title: "AinB_DatasetClean"
author: "Andrea Iglesias"
date: "12/12/2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Dataset cleansing

```{r echo=FALSE}
people <- read.csv("/Users/Josef/Desktop/peoplepickinganonymised.csv", header=TRUE)
friendship <- subset(people, select = -c(1:3,64:length(people)))
advice <- subset(people, select = -c(1:63, 124:length(people)))
creat <- subset(people, select = -c(1:123, 184:length(people)))
implem <-subset(people, select = -c(1:183, 244:length(people)))
infl <-subset(people, select = -c(1:243, 304:364))
```

```{r echo=FALSE}
colnames(friendship) <- seq(1,60,by=1)
colnames(creat) <- seq(1,60,by=1)
colnames(implem) <- seq(1,60,by=1)
colnames(infl) <- seq(1,60,by=1)
```

```{r echo=FALSE}
friendship[row(friendship) == col(friendship)] <- 0
creat[row(creat) == col(creat)] <- 0
implem[row(implem) == col(implem)] <- 0
infl[row(infl) == col(infl)] <- 0
```

```{r}
write.csv(friendship, "friendshipmat.csv")
write.csv(creat, "creatmat.csv")
write.csv(implem, "implemmat.csv")
write.csv(infl, "inflmat.csv")
```

